-- =====================================================================
-- Script de creación de la base de datos ESTUD-IA
-- Motor: Microsoft SQL Server 2019 o superior
-- =====================================================================
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'estudia_db')
BEGIN
    CREATE DATABASE estudia_db;
END
GO
USE estudia_db;
GO
 
-- Tabla: USUARIO (Entidad fuerte)
CREATE TABLE USUARIO (
  [idUsuario] INT IDENTITY(1,1) NOT NULL,
  [nombres] NVARCHAR(80) NOT NULL,
  [apellidos] NVARCHAR(80) NOT NULL,
  [correo] NVARCHAR(120) NOT NULL UNIQUE,
  [contrasena] NVARCHAR(255) NOT NULL,
  [telefono] NVARCHAR(20) NULL,
  [rol] NVARCHAR(20) NOT NULL CHECK ([rol] IN ('ADMINISTRADOR', 'ESTUDIANTE', 'DOCENTE', 'DESARROLLADOR')),
  [fechaRegistro] DATETIME2 NOT NULL DEFAULT (SYSDATETIME()),
  CONSTRAINT PK_USUARIO PRIMARY KEY (idUsuario)
);
GO
 
-- Tabla: CURSO (Entidad fuerte)
CREATE TABLE CURSO (
  [idCurso] INT IDENTITY(1,1) NOT NULL,
  [nombreCurso] NVARCHAR(100) NOT NULL,
  [descripcion] NVARCHAR(255) NULL,
  [duracion] INT NULL,
  [precio] DECIMAL(10,2) NOT NULL,
  CONSTRAINT PK_CURSO PRIMARY KEY (idCurso)
);
GO
 
-- Tabla: GRUPO (Entidad fuerte)
CREATE TABLE GRUPO (
  [idGrupo] INT IDENTITY(1,1) NOT NULL,
  [idCurso] INT NOT NULL,
  [idDocente] INT NULL,
  [nombreGrupo] NVARCHAR(60) NOT NULL,
  [fechaInicio] DATE NOT NULL,
  [fechaFin] DATE NULL,
  [horario] NVARCHAR(60) NULL,
  [cupos] INT NOT NULL,
  [estado] NVARCHAR(20) NOT NULL DEFAULT ('PROGRAMADO') CHECK ([estado] IN ('PROGRAMADO', 'EN_CURSO', 'FINALIZADO')),
  CONSTRAINT PK_GRUPO PRIMARY KEY (idGrupo),
  CONSTRAINT FK_GRUPO_idCurso FOREIGN KEY (idCurso) REFERENCES CURSO(idCurso) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_GRUPO_idDocente FOREIGN KEY (idDocente) REFERENCES USUARIO(idUsuario) ON DELETE SET NULL ON UPDATE NO ACTION
);
GO
 
-- Tabla: ADMINISTRADOR (Especialización (Estrategia A))
CREATE TABLE ADMINISTRADOR (
  [idUsuario] INT NOT NULL,
  [cargo] NVARCHAR(60) NULL,
  [permisos] NVARCHAR(150) NULL,
  CONSTRAINT PK_ADMINISTRADOR PRIMARY KEY (idUsuario),
  CONSTRAINT FK_ADMINISTRADOR_idUsuario FOREIGN KEY (idUsuario) REFERENCES USUARIO(idUsuario) ON DELETE CASCADE ON UPDATE NO ACTION
);
GO
 
-- Tabla: ESTUDIANTE (Especialización (Estrategia A))
CREATE TABLE ESTUDIANTE (
  [idUsuario] INT NOT NULL,
  [dni] NVARCHAR(8) NOT NULL UNIQUE,
  [idGrupo] INT NULL,
  CONSTRAINT PK_ESTUDIANTE PRIMARY KEY (idUsuario),
  CONSTRAINT FK_ESTUDIANTE_idUsuario FOREIGN KEY (idUsuario) REFERENCES USUARIO(idUsuario) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT FK_ESTUDIANTE_idGrupo FOREIGN KEY (idGrupo) REFERENCES GRUPO(idGrupo) ON DELETE SET NULL ON UPDATE NO ACTION
);
GO
 
-- Tabla: APODERADO (Entidad débil (depende de ESTUDIANTE))
CREATE TABLE APODERADO (
  [idApoderado] INT IDENTITY(1,1) NOT NULL,
  [idEstudiante] INT NOT NULL,
  [nombre] NVARCHAR(80) NOT NULL,
  [apellidos] NVARCHAR(80) NOT NULL,
  [parentesco] NVARCHAR(30) NULL,
  [direccion] NVARCHAR(150) NULL,
  [celular] NVARCHAR(20) NOT NULL,
  CONSTRAINT PK_APODERADO PRIMARY KEY (idApoderado),
  CONSTRAINT FK_APODERADO_idEstudiante FOREIGN KEY (idEstudiante) REFERENCES ESTUDIANTE(idUsuario) ON DELETE CASCADE ON UPDATE NO ACTION
);
GO
 
-- Tabla: SESION (Entidad débil (depende de GRUPO))
CREATE TABLE SESION (
  [idSesion] INT IDENTITY(1,1) NOT NULL,
  [idGrupo] INT NOT NULL,
  [fecha] DATE NOT NULL,
  [horaInicio] TIME NULL,
  [horaFin] TIME NULL,
  [modalidad] NVARCHAR(15) NOT NULL CHECK ([modalidad] IN ('PRESENCIAL', 'VIRTUAL')),
  [tema] NVARCHAR(150) NULL,
  [estado] NVARCHAR(15) NOT NULL DEFAULT ('PROGRAMADA') CHECK ([estado] IN ('PROGRAMADA', 'DICTADA', 'CANCELADA')),
  CONSTRAINT PK_SESION PRIMARY KEY (idSesion),
  CONSTRAINT FK_SESION_idGrupo FOREIGN KEY (idGrupo) REFERENCES GRUPO(idGrupo) ON DELETE CASCADE ON UPDATE NO ACTION
);
GO
 
-- Tabla: MATRICULA (Entidad asociativa (ESTUDIANTE–GRUPO))
CREATE TABLE MATRICULA (
  [idMatricula] INT IDENTITY(1,1) NOT NULL,
  [idEstudiante] INT NOT NULL,
  [idGrupo] INT NOT NULL,
  [fechaMatricula] DATE NOT NULL DEFAULT (CAST(GETDATE() AS DATE)),

  [estadoMatricula] NVARCHAR(15) NOT NULL DEFAULT ('ACTIVA') CHECK ([estadoMatricula] IN ('ACTIVA', 'RETIRADA', 'FINALIZADA')),
  [observaciones] NVARCHAR(200) NULL,
  CONSTRAINT PK_MATRICULA PRIMARY KEY (idMatricula),
  CONSTRAINT FK_MATRICULA_idEstudiante FOREIGN KEY (idEstudiante) REFERENCES ESTUDIANTE(idUsuario) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_MATRICULA_idGrupo FOREIGN KEY (idGrupo) REFERENCES GRUPO(idGrupo) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT UQ_MATRICULA_1 UNIQUE (idEstudiante, idGrupo)
);
GO
 
-- Tabla: ASISTENCIA (Entidad débil (depende de SESIÓN))
CREATE TABLE ASISTENCIA (
  [idAsistencia] INT IDENTITY(1,1) NOT NULL,
  [idSesion] INT NOT NULL,
  [idEstudiante] INT NOT NULL,
  [fecha] DATE NOT NULL,
  [estadoAsistencia] NVARCHAR(15) NOT NULL CHECK ([estadoAsistencia] IN ('PRESENTE', 'TARDANZA', 'AUSENTE', 'JUSTIFICADO')),
  [observacion] NVARCHAR(150) NULL,
  CONSTRAINT PK_ASISTENCIA PRIMARY KEY (idAsistencia),
  CONSTRAINT FK_ASISTENCIA_idSesion FOREIGN KEY (idSesion) REFERENCES SESION(idSesion) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_ASISTENCIA_idEstudiante FOREIGN KEY (idEstudiante) REFERENCES ESTUDIANTE(idUsuario) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT UQ_ASISTENCIA_1 UNIQUE (idSesion, idEstudiante)
);
GO
 
-- Tabla: NOTA (Entidad débil (depende de ESTUDIANTE y CURSO))
CREATE TABLE NOTA (
  [idNota] INT IDENTITY(1,1) NOT NULL,
  [idEstudiante] INT NOT NULL,
  [idCurso] INT NOT NULL,
  [tipoEvaluacion] NVARCHAR(50) NOT NULL,
  [nota] DECIMAL(4,2) NOT NULL CHECK (nota BETWEEN 0 AND 20),
  [observacion] NVARCHAR(150) NULL,
  [fechaRegistro] DATE NOT NULL DEFAULT (CAST(GETDATE() AS DATE)),
  CONSTRAINT PK_NOTA PRIMARY KEY (idNota),
  CONSTRAINT FK_NOTA_idEstudiante FOREIGN KEY (idEstudiante) REFERENCES ESTUDIANTE(idUsuario) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_NOTA_idCurso FOREIGN KEY (idCurso) REFERENCES CURSO(idCurso) ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO
 
-- Tabla: TAREA (Entidad fuerte (depende de CURSO))
CREATE TABLE TAREA (
  [idTarea] INT IDENTITY(1,1) NOT NULL,
  [idCurso] INT NOT NULL,
  [titulo] NVARCHAR(120) NOT NULL,
  [descripcion] NVARCHAR(255) NULL,
  [fechaPublicacion] DATE NOT NULL,
  [fechaEntrega] DATE NOT NULL,
  [archivoAdjunto] NVARCHAR(255) NULL,
  [estado] NVARCHAR(15) NOT NULL DEFAULT ('ABIERTA') CHECK ([estado] IN ('ABIERTA', 'CERRADA')),
  CONSTRAINT PK_TAREA PRIMARY KEY (idTarea),
  CONSTRAINT FK_TAREA_idCurso FOREIGN KEY (idCurso) REFERENCES CURSO(idCurso) ON DELETE CASCADE ON UPDATE NO ACTION
);
GO
 
-- Tabla: ENTREGA_TAREA (Entidad asociativa (TAREA–ESTUDIANTE))
CREATE TABLE ENTREGA_TAREA (
  [idEntrega] INT IDENTITY(1,1) NOT NULL,
  [idTarea] INT NOT NULL,
  [idEstudiante] INT NOT NULL,
  [archivoEntregado] NVARCHAR(255) NULL,
  [fechaEntrega] DATETIME2 NOT NULL DEFAULT (SYSDATETIME()),
  [calificacion] DECIMAL(4,2) NULL CHECK (calificacion BETWEEN 0 AND 20),
  [estado] NVARCHAR(15) NOT NULL DEFAULT ('ENTREGADA') CHECK ([estado] IN ('ENTREGADA', 'CALIFICADA', 'FUERA_DE_PLAZO')),
  [observacion] NVARCHAR(150) NULL,
  CONSTRAINT PK_ENTREGA_TAREA PRIMARY KEY (idEntrega),
  CONSTRAINT FK_ENTREGA_TAREA_idTarea FOREIGN KEY (idTarea) REFERENCES TAREA(idTarea) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_ENTREGA_TAREA_idEstudiante FOREIGN KEY (idEstudiante) REFERENCES ESTUDIANTE(idUsuario) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT UQ_ENTREGA_TAREA_1 UNIQUE (idTarea, idEstudiante)
);
GO
 
-- Tabla: CLIENTE (Entidad fuerte)
CREATE TABLE CLIENTE (
  [idCliente] INT IDENTITY(1,1) NOT NULL,
  [ruc] NVARCHAR(11) NOT NULL UNIQUE,
  [representante] NVARCHAR(100) NULL,
  [correo] NVARCHAR(120) NULL,
  [direccion] NVARCHAR(150) NULL,
  [telefono] NVARCHAR(20) NULL,
  [estadoCliente] NVARCHAR(10) NOT NULL DEFAULT ('ACTIVO') CHECK ([estadoCliente] IN ('ACTIVO', 'INACTIVO')),
  CONSTRAINT PK_CLIENTE PRIMARY KEY (idCliente)
);
GO
 
-- Tabla: PROPUESTA (Entidad fuerte (depende de CLIENTE))
CREATE TABLE PROPUESTA (
  [idPropuesta] INT IDENTITY(1,1) NOT NULL,
  [idCliente] INT NOT NULL,
  [descripcion] NVARCHAR(255) NULL,
  [monto] DECIMAL(10,2) NOT NULL,
  [fechaEmision] DATE NOT NULL,
  [fechaRespuesta] DATE NULL,
  [estado] NVARCHAR(15) NOT NULL DEFAULT ('PENDIENTE') CHECK ([estado] IN ('PENDIENTE', 'APROBADA', 'RECHAZADA')),
  CONSTRAINT PK_PROPUESTA PRIMARY KEY (idPropuesta),
  CONSTRAINT FK_PROPUESTA_idCliente FOREIGN KEY (idCliente) REFERENCES CLIENTE(idCliente) ON DELETE CASCADE ON UPDATE NO ACTION
);
GO
 
-- Tabla: SERVICIO (Entidad fuerte)
CREATE TABLE SERVICIO (
  [idServicio] INT IDENTITY(1,1) NOT NULL,
  [idPropuesta] INT NOT NULL UNIQUE,
  [idCliente] INT NOT NULL,
  [nombreServicio] NVARCHAR(100) NOT NULL,
  [descripcion] NVARCHAR(255) NULL,
  [precio] DECIMAL(10,2) NOT NULL,
  [estado] NVARCHAR(15) NOT NULL DEFAULT ('ACTIVO') CHECK ([estado] IN ('ACTIVO', 'PAUSADO', 'FINALIZADO')),
  CONSTRAINT PK_SERVICIO PRIMARY KEY (idServicio),
  CONSTRAINT FK_SERVICIO_idPropuesta FOREIGN KEY (idPropuesta) REFERENCES PROPUESTA(idPropuesta) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_SERVICIO_idCliente FOREIGN KEY (idCliente) REFERENCES CLIENTE(idCliente) ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO
 
-- Tabla: CONTRATO (Entidad fuerte (depende de SERVICIO))
CREATE TABLE CONTRATO (
  [idContrato] INT IDENTITY(1,1) NOT NULL,
  [idServicio] INT NOT NULL,
  [idCliente] INT NOT NULL,
  [monto] DECIMAL(10,2) NOT NULL,
  [fechaFin] DATE NULL,
  [estadoContratado] NVARCHAR(10) NOT NULL DEFAULT ('VIGENTE') CHECK ([estadoContratado] IN ('VIGENTE', 'CERRADO')),
  [archivoContrato] NVARCHAR(255) NULL,
  CONSTRAINT PK_CONTRATO PRIMARY KEY (idContrato),
  CONSTRAINT FK_CONTRATO_idServicio FOREIGN KEY (idServicio) REFERENCES SERVICIO(idServicio) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_CONTRATO_idCliente FOREIGN KEY (idCliente) REFERENCES CLIENTE(idCliente) ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO
 
-- Tabla: PROYECTO (Entidad fuerte)
CREATE TABLE PROYECTO (
  [idProyecto] INT IDENTITY(1,1) NOT NULL,
  [nombreProyecto] NVARCHAR(120) NOT NULL,
  [descripcion] NVARCHAR(255) NULL,
  [tipoSolucion] NVARCHAR(60) NULL,
  [fechaInicio] DATE NOT NULL,
  [fechaLimite] DATE NOT NULL,
  [estado] NVARCHAR(15) NOT NULL DEFAULT ('DISENO') CHECK ([estado] IN ('DISENO', 'DESARROLLO', 'PRUEBAS', 'FINALIZADO')),
  [repositorio] NVARCHAR(255) NULL,
  CONSTRAINT PK_PROYECTO PRIMARY KEY (idProyecto)
);
GO
 
-- Tabla: INTEGRANTE_PROYECTO (Entidad asociativa (USUARIO–PROYECTO, N:M))
CREATE TABLE INTEGRANTE_PROYECTO (
  [idIntegrante] INT IDENTITY(1,1) NOT NULL,
  [idUsuario] INT NOT NULL,
  [idProyecto] INT NOT NULL,
  [fechaAsignacion] DATE NOT NULL DEFAULT (CAST(GETDATE() AS DATE)),
  [rolProyecto] NVARCHAR(60) NULL,
  CONSTRAINT PK_INTEGRANTE_PROYECTO PRIMARY KEY (idIntegrante),
  CONSTRAINT FK_INTEGRANTE_PROYECTO_idUsuario FOREIGN KEY (idUsuario) REFERENCES USUARIO(idUsuario) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_INTEGRANTE_PROYECTO_idProyecto FOREIGN KEY (idProyecto) REFERENCES PROYECTO(idProyecto) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT UQ_INTEGRANTE_PROYECTO_1 UNIQUE (idUsuario, idProyecto)
);
GO
 
-- Tabla: PAGO (Entidad débil (depende de USUARIO))
CREATE TABLE PAGO (
  [idPago] INT IDENTITY(1,1) NOT NULL,
  [idUsuario] INT NOT NULL,
  [idMatricula] INT NULL,
  [idServicio] INT NULL,
  [monto] DECIMAL(10,2) NOT NULL,
  [medioPago] NVARCHAR(15) NOT NULL CHECK ([medioPago] IN ('YAPE', 'TRANSFERENCIA', 'EFECTIVO', 'PLIN')),
  [comprobante] NVARCHAR(255) NULL,
  [fechaPago] DATETIME2 NOT NULL DEFAULT (SYSDATETIME()),
  [estadoPago] NVARCHAR(15) NOT NULL DEFAULT ('PENDIENTE') CHECK ([estadoPago] IN ('PAGADO', 'PENDIENTE', 'EN_MORA')),
  [fechaVerificacion] DATETIME2 NULL,
  CONSTRAINT PK_PAGO PRIMARY KEY (idPago),
  CONSTRAINT FK_PAGO_idUsuario FOREIGN KEY (idUsuario) REFERENCES USUARIO(idUsuario) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_PAGO_idMatricula FOREIGN KEY (idMatricula) REFERENCES MATRICULA(idMatricula) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT FK_PAGO_idServicio FOREIGN KEY (idServicio) REFERENCES SERVICIO(idServicio) ON DELETE SET NULL ON UPDATE NO ACTION
);
GO
 
-- Tabla: COMUNICACION (Entidad débil (depende de USUARIO y/o CLIENTE))
CREATE TABLE COMUNICACION (
  [idComunicacion] INT IDENTITY(1,1) NOT NULL,
  [idUsuario] INT NULL,
  [idCliente] INT NULL,
  [tipoComunicacion] NVARCHAR(20) NOT NULL CHECK ([tipoComunicacion] IN ('CONSULTA', 'ALERTA', 'TICKET_SOPORTE', 'SEGUIMIENTO')),
  [asunto] NVARCHAR(120) NULL,
  [detalle] NVARCHAR(255) NULL,
  [canal] NVARCHAR(40) NULL,
  [fecha] DATETIME2 NOT NULL DEFAULT (SYSDATETIME()),
  [estado] NVARCHAR(15) NOT NULL DEFAULT ('ABIERTO') CHECK ([estado] IN ('ABIERTO', 'ASIGNADO', 'RESUELTO', 'CERRADO')),
  [tiempoAtencionHoras] DECIMAL(6,2) NULL,
  CONSTRAINT PK_COMUNICACION PRIMARY KEY (idComunicacion),
  CONSTRAINT FK_COMUNICACION_idUsuario FOREIGN KEY (idUsuario) REFERENCES USUARIO(idUsuario) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT FK_COMUNICACION_idCliente FOREIGN KEY (idCliente) REFERENCES CLIENTE(idCliente) ON DELETE SET NULL ON UPDATE NO ACTION
);
GO
 
-- Tabla: NOTIFICACION (Entidad débil (depende de USUARIO))
CREATE TABLE NOTIFICACION (
  [idNotificacion] INT IDENTITY(1,1) NOT NULL,
  [idUsuario] INT NOT NULL,
  [titulo] NVARCHAR(100) NOT NULL,
  [descripcion] NVARCHAR(255) NULL,
  [fecha] DATETIME2 NOT NULL DEFAULT (SYSDATETIME()),
  [estadoNotificacion] NVARCHAR(10) NOT NULL DEFAULT ('ENVIADA') CHECK ([estadoNotificacion] IN ('ENVIADA', 'LEIDA')),
  CONSTRAINT PK_NOTIFICACION PRIMARY KEY (idNotificacion),
  CONSTRAINT FK_NOTIFICACION_idUsuario FOREIGN KEY (idUsuario) REFERENCES USUARIO(idUsuario) ON DELETE CASCADE ON UPDATE NO ACTION
);
GO
 
-- Tabla: REPORTE (Entidad fuerte)
CREATE TABLE REPORTE (
  [idReporte] INT IDENTITY(1,1) NOT NULL,
  [tipoReporte] NVARCHAR(60) NOT NULL,
  [fechaGeneracion] DATETIME2 NOT NULL DEFAULT (SYSDATETIME()),
  [generadoPor] INT NOT NULL,
  [archivoReporte] NVARCHAR(255) NULL,
  CONSTRAINT PK_REPORTE PRIMARY KEY (idReporte),
  CONSTRAINT FK_REPORTE_generadoPor FOREIGN KEY (generadoPor) REFERENCES USUARIO(idUsuario) ON DELETE NO ACTION ON UPDATE NO ACTION
);
GO
 
-- Tabla: MENSAJE_CONTACTO (Entidad débil)
CREATE TABLE MENSAJE_CONTACTO (
  [idMensaje] INT IDENTITY(1,1) NOT NULL,
  [nombre] NVARCHAR(100) NOT NULL,
  [telefono] NVARCHAR(20) NULL UNIQUE,
  [correo] NVARCHAR(120) NULL UNIQUE,
  [mensaje] NVARCHAR(255) NOT NULL,
  [fechaEnvio] DATETIME2 NOT NULL DEFAULT (SYSDATETIME()),
  [estadoMensaje] NVARCHAR(10) NOT NULL DEFAULT ('NUEVO') CHECK ([estadoMensaje] IN ('NUEVO', 'ATENDIDO')),
  CONSTRAINT PK_MENSAJE_CONTACTO PRIMARY KEY (idMensaje)
);
GO
 
